server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    
    resolver 10.96.0.10 valid=30s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $backend_upstream fullstack-app-backend;
        proxy_pass http://$backend_upstream:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}